In [47]:
# AIG150 Supplementary Exam
# Max Marks 60
# Time Allowed: 60 Minutes

# Instructions

#	You are allowed to bring a reference sheet (A4-both sided).
#	Use font “Arial- size 10” minimium, print your name on top of the reference sheet.
#	The sheet must be submitted with the test.
#	As a Seneca student, you must conduct yourself in an honest and trustworthy manner in all aspects of your academic career.
#   A dishonest attempt to obtain an academic advantage is considered an offense and will not be tolerated by the college. 
#   Rename the file with the student name
#  Once you are done, upload the file on BB ( ONLY ONE SUBMISSION IS ALLOWED)

In [48]:
# Download the given csv file

In [49]:
import pandas as pd
stroke=pd.read_csv('stroke.csv')
print(stroke)

          id  gender   age  hypertension  heart_disease ever_married  \
0      30669    Male   3.0             0              0           No
1      30468    Male  58.0             1              0          Yes
2      16523  Female   8.0             0              0           No
3      56543  Female  70.0             0              0          Yes
4      46136    Male  14.0             0              0           No
...      ...     ...   ...           ...            ...          ...
43395  56196  Female  10.0             0              0           No
43396   5450  Female  56.0             0              0          Yes
43397  28375  Female  82.0             1              0          Yes
43398  27973    Male  40.0             0              0          Yes
43399  36271  Female  82.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0          children          Rural              95.12  18.0              NaN
1           Private          Urban              87.96  39.2     never smoked
2           Private          Urban             110.89  17.6              NaN
3           Private          Rural              69.04  35.9  formerly smoked
4      Never_worked          Rural             161.28  19.1              NaN
...             ...            ...                ...   ...              ...
43395      children          Urban              58.64  20.4     never smoked
43396      Govt_job          Urban             213.61  55.4  formerly smoked
43397       Private          Urban              91.94  28.9  formerly smoked
43398       Private          Urban              99.16  33.2     never smoked
43399       Private          Urban              79.48  20.6     never smoked

       stroke
0           0
1           0
2           0
3           0
4           0
...       ...
43395       0
43396       0
43397       0
43398       0
43399       0

[43400 rows x 12 columns]

In [50]:
# Using the stroke dataframe, you have to write commands for Q 1-10.
# Each command is worth 3 marks [ In total 30 marks].

In [51]:
#1. Show the frequency distribution of the gender column.

In [52]:
stroke['gender'].value_counts()

gender
Female    25665
Male      17724
Other        11
Name: count, dtype: int64

In [53]:
#2. Lowercase all values under the gender column in the stroke dataframe.

In [54]:
stroke['gender'] = stroke['gender'].str.lower()
stroke['gender']

0          male
1          male
2        female
3        female
4          male
          ...
43395    female
43396    female
43397    female
43398      male
43399    female
Name: gender, Length: 43400, dtype: object

In [55]:
#3. Replace all female occurrences with "f" and all the male occurrences with "m" under the gender column in the stroke dataframe.

In [56]:
stroke['gender'] = stroke['gender'].replace('female', 'f').replace('male', 'm')
stroke['gender']

0        m
1        m
2        f
3        f
4        m
        ..
43395    f
43396    f
43397    f
43398    m
43399    f
Name: gender, Length: 43400, dtype: object

In [57]:
#4. Add a column named 'gender_bin' to the stroke dataframe that takes the value 1 if gender is equal to the string literal 'm' and 0 otherwise.

In [58]:
stroke['gender_bin'] = (stroke['gender']=='m').astype(int)
stroke['gender_bin']

0        1
1        1
2        0
3        0
4        1
        ..
43395    0
43396    0
43397    0
43398    1
43399    0
Name: gender_bin, Length: 43400, dtype: int64

In [59]:
#5. For male observations, replace the missing values under the age column with the mean age of all male observations.

In [ ]:
mean_age = stroke.loc[stroke['gender']=='m', 'age'].mean()
stroke.loc[stroke['gender']=='m', 'age'] = mean_age
stroke['age']

0        41.469727
1        41.469727
2         8.000000
3        70.000000
4        41.469727
           ...
43395    10.000000
43396    56.000000
43397    82.000000
43398    41.469727
43399    82.000000
Name: age, Length: 43400, dtype: float64

In [ ]:
#6. Write the code to show the rows of the stroke dataframe where there are outliers for the avg_glucose_level variable.
#   Outliers should be considered based on the mean and standard deviation method.Any value greater than the mean +2*SD or
#  lower than mean-2*SD is considered as outlier.

In [74]:
mean_glucose_level = stroke['avg_glucose_level'].mean()
standard_glucose_level = stroke['avg_glucose_level'].std()

for i_index, i_row in stroke.iterrows():
    if (i_row['avg_glucose_level']> (mean_glucose_level + 2*standard_glucose_level)) or (i_row['avg_glucose_level']< (mean_glucose_level - 2*standard_glucose_level)):
        print(f'outlier row --> {i_row}')
        print(i_index)

outlier row --> id                     32257
gender                     f
age                     47.0
hypertension               0
heart_disease              0
ever_married             Yes
work_type            Private
Residence_type         Urban
avg_glucose_level     210.95
bmi                     50.1
smoking_status           NaN
stroke                     0
gender_bin                 0
Name: 5, dtype: object
5
outlier row --> id                           41413
gender                           f
age                           75.0
hypertension                     0
heart_disease                    1
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           243.53
bmi                           27.0
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 7, dtype: object
7
outlier row --> id                           28674
gender                           f
age                           74.0
hypertension                     1
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level           205.84
bmi                           54.6
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 9, dtype: object
9
outlier row --> id                              4057
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Urban
avg_glucose_level             198.21
bmi                             27.3
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 23, dtype: object
23
outlier row --> id                          36275
gender                          f
age                          54.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          206.72
bmi                          26.7
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 28, dtype: object
28
outlier row --> id                           11577
gender                           f
age                           70.0
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           214.45
bmi                           31.2
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 29, dtype: object
29
outlier row --> id                           28526
gender                           m
age                      41.469727
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           203.04
bmi                           33.6
smoking_status        never smoked
stroke                           0
gender_bin                       1
Name: 49, dtype: object
49
outlier row --> id                       18518
gender                       m
age                  41.469727
hypertension                 0
heart_disease                0
ever_married               Yes
work_type              Private
Residence_type           Rural
avg_glucose_level        242.3
bmi                       35.3
smoking_status          smokes
stroke                       0
gender_bin                   1
Name: 54, dtype: object
54
outlier row --> id                       42807
gender                       m
age                  41.469727
hypertension                 0
heart_disease                0
ever_married               Yes
work_type             Govt_job
Residence_type           Urban
avg_glucose_level       220.49
bmi                       43.1
smoking_status             NaN
stroke                       0
gender_bin                   1
Name: 58, dtype: object
58
outlier row --> id                              9046
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      1
ever_married                     Yes
work_type                    Private
Residence_type                 Urban
avg_glucose_level             228.69
bmi                             36.6
smoking_status       formerly smoked
stroke                             1
gender_bin                         1
Name: 63, dtype: object
63
outlier row --> id                          11120
gender                          f
age                          78.0
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Urban
avg_glucose_level          218.46
bmi                          34.3
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 66, dtype: object
66
outlier row --> id                             68614
gender                             f
age                             48.0
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Rural
avg_glucose_level              216.7
bmi                             38.7
smoking_status       formerly smoked
stroke                             0
gender_bin                         0
Name: 70, dtype: object
70
outlier row --> id                              4480
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Rural
avg_glucose_level             234.58
bmi                             34.3
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 77, dtype: object
77
outlier row --> id                           2982
gender                          f
age                          57.0
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          235.85
bmi                          40.1
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 78, dtype: object
78
outlier row --> id                           51676
gender                           f
age                           61.0
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           202.21
bmi                            NaN
smoking_status        never smoked
stroke                           1
gender_bin                       0
Name: 81, dtype: object
81
outlier row --> id                          59368
gender                          f
age                          78.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Urban
avg_glucose_level           243.5
bmi                          26.1
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 83, dtype: object
83
outlier row --> id                           21130
gender                           m
age                      41.469727
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level           229.92
bmi                           25.9
smoking_status              smokes
stroke                           0
gender_bin                       1
Name: 85, dtype: object
85
outlier row --> id                          56357
gender                          f
age                          82.0
hypertension                    0
heart_disease                   1
ever_married                   No
work_type                 Private
Residence_type              Urban
avg_glucose_level           215.6
bmi                          24.9
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 90, dtype: object
90
outlier row --> id                             45053
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                   Govt_job
Residence_type                 Urban
avg_glucose_level             239.64
bmi                             34.6
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 96, dtype: object
96
outlier row --> id                             28333
gender                             f
age                             79.0
hypertension                       1
heart_disease                      1
ever_married                     Yes
work_type              Self-employed
Residence_type                 Urban
avg_glucose_level             200.28
bmi                             30.0
smoking_status       formerly smoked
stroke                             0
gender_bin                         0
Name: 103, dtype: object
103
outlier row --> id                          49421
gender                          f
age                          66.0
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          205.23
bmi                          39.5
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 108, dtype: object
108
outlier row --> id                           54312
gender                           f
age                           76.0
hypertension                     1
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level           209.58
bmi                            NaN
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 113, dtype: object
113
outlier row --> id                             69037
gender                             f
age                             72.0
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Rural
avg_glucose_level             210.78
bmi                             32.3
smoking_status       formerly smoked
stroke                             0
gender_bin                         0
Name: 118, dtype: object
118
outlier row --> id                           63732
gender                           m
age                      41.469727
hypertension                     1
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level            251.6
bmi                           27.1
smoking_status        never smoked
stroke                           0
gender_bin                       1
Name: 139, dtype: object
139
outlier row --> id                           2374
gender                          m
age                     41.469727
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          213.37
bmi                          36.0
smoking_status       never smoked
stroke                          0
gender_bin                      1
Name: 150, dtype: object
150
outlier row --> id                             15528
gender                             m
age                        41.469727
hypertension                       1
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Rural
avg_glucose_level             223.36
bmi                             41.5
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 153, dtype: object
153
outlier row --> id                          22320
gender                          f
age                          37.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Urban
avg_glucose_level          203.81
bmi                          46.6
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 171, dtype: object
171
outlier row --> id                          50305
gender                          f
age                          56.0
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          205.26
bmi                          40.3
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 180, dtype: object
180
outlier row --> id                             59729
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      0
ever_married                     Yes
work_type                    Private
Residence_type                 Urban
avg_glucose_level             211.03
bmi                             34.2
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 183, dtype: object
183
outlier row --> id                           12985
gender                           f
age                           69.0
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level           225.47
bmi                           36.9
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 187, dtype: object
187
outlier row --> id                           17291
gender                           f
age                           63.0
hypertension                     1
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Rural
avg_glucose_level            227.1
bmi                           26.9
smoking_status                 NaN
stroke                           0
gender_bin                       0
Name: 198, dtype: object
198
outlier row --> id                             66196
gender                             m
age                        41.469727
hypertension                       0
heart_disease                      1
ever_married                      No
work_type                    Private
Residence_type                 Rural
avg_glucose_level             201.76
bmi                             30.2
smoking_status       formerly smoked
stroke                             0
gender_bin                         1
Name: 210, dtype: object
210
outlier row --> id                           35846
gender                           f
age                           43.0
hypertension                     1
heart_disease                    0
ever_married                    No
work_type            Self-employed
Residence_type               Rural
avg_glucose_level            217.3
bmi                           27.5
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 221, dtype: object
221
outlier row --> id                          28645
gender                          f
age                          38.0
hypertension                    1
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Urban
avg_glucose_level          196.01
bmi                          28.1
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 222, dtype: object
222
outlier row --> id                       15649
gender                       m
age                  41.469727
hypertension                 1
heart_disease                0
ever_married               Yes
work_type              Private
Residence_type           Rural
avg_glucose_level       198.69
bmi                        NaN
smoking_status          smokes
stroke                       0
gender_bin                   1
Name: 233, dtype: object
233
outlier row --> id                            545
gender                          m
age                     41.469727
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Rural
avg_glucose_level          210.48
bmi                          71.9
smoking_status       never smoked
stroke                          0
gender_bin                      1
Name: 302, dtype: object
302
outlier row --> id                          15791
gender                          m
age                     41.469727
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                 Private
Residence_type              Urban
avg_glucose_level          193.83
bmi                          26.5
smoking_status       never smoked
stroke                          0
gender_bin                      1
Name: 307, dtype: object
307
outlier row --> id                       68275
gender                       m
age                  41.469727
hypertension                 0
heart_disease                0
ever_married               Yes
work_type              Private
Residence_type           Urban
avg_glucose_level       247.69
bmi                       35.1
smoking_status             NaN
stroke                       0
gender_bin                   1
Name: 310, dtype: object
310
outlier row --> id                          36561
gender                          f
age                          39.0
hypertension                    0
heart_disease                   0
ever_married                  Yes
work_type                Govt_job
Residence_type              Rural
avg_glucose_level          191.47
bmi                          28.3
smoking_status       never smoked
stroke                          0
gender_bin                      0
Name: 317, dtype: object
317
outlier row --> id                           47811
gender                           f
age                           72.0
hypertension                     0
heart_disease                    0
ever_married                   Yes
work_type            Self-employed
Residence_type               Urban
avg_glucose_level           239.82
bmi                           35.8
smoking_status        never smoked
stroke                           0
gender_bin                       0
Name: 322, dtype: object
322
outlier row --> id                       56179
gender                       m
age                  41.469727
hypertension                 0
heart_disease                0
ever_married                No
work_type              Private

In [ ]:
#7.Replace all the missing values in stroke dataframe using a linear interpolation and print the top rows of the dataset.

In [75]:
stroke = stroke.interpolate(method='linear')

C:\Users\W1tcher\AppData\Local\Temp\ipykernel_24376\1477254514.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  stroke = stroke.interpolate(method='linear')

In [76]:
stroke

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,gender_bin
0,30669,m,41.469727,0,0,No,children,Rural,95.12,18.0,NaN,0,1
1,30468,m,41.469727,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0,1
2,16523,f,8.000000,0,0,No,Private,Urban,110.89,17.6,NaN,0,0
3,56543,f,70.000000,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0,0
4,46136,m,41.469727,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,f,10.000000,0,0,No,children,Urban,58.64,20.4,never smoked,0,0
43396,5450,f,56.000000,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0,0
43397,28375,f,82.000000,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0,0
43398,27973,m,41.469727,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0,1
43399,36271,f,82.000000,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0,0

In [ ]:
#8.Write a paragraph to highlight the differences between the fill foward/backward versus linear interpolation of the missing values.

Forward fill (ffill) and backward fill (bfill) propagate the last known or next known value, respectively, to fill missing values. These methods work well for time-series data where missing values are assumed to follow the previous trend. However, they do not estimate intermediate values based on a trend. In contrast, linear interpolation calculates missing values by assuming a straight-line relationship between known data points. It provides a more accurate estimate when data follows a continuous trend, unlike ffill or bfill, which may introduce bias by repeating values. Linear interpolation is ideal for numerical datasets with gradual changes, while forward and backward fill are better suited for categorical or sequential data where trends remain consistent over time.

In [ ]:
#9.Add a new column named "new_age" in the stroke dataframe, Use lambda function to fill this col with the age after 10 years (hint: Add 10 to current age)

In [78]:
stroke['new_age'] = stroke['age'].apply(lambda x: x+10)
stroke['new_age']

0        51.469727
1        51.469727
2        18.000000
3        80.000000
4        51.469727
           ...
43395    20.000000
43396    66.000000
43397    92.000000
43398    51.469727
43399    92.000000
Name: new_age, Length: 43400, dtype: float64

In [ ]:
#10.Create a histogram to show the frequency of male and female observations.

In [77]:
customer=pd.read_csv('customer.csv')
invoice=pd.read_csv('invoice.csv')
print(customer)
print(invoice)
# Use the invoice and customer dataframes to answer q11-15
# Each question is worth 6 marks

   Unnamed: 0  CUS_CODE CUS_LNAME CUS_FNAME
0           0     10010     Ramas    Alfred
1           1     10011     Dunne     Leona
2           2     10012     Smith     Kathy
3           3     10013   Olowski      Paul
4           4     10014   Orlando     Myron
5           5     10015   O'Brian       Amy
6           6     10016     Brown     James
7           7     10017  Williams    George
8           8     10018   Farriss      Anne
9           9     10019     Smith    Olette
   Unnamed: 0  INV_NUMBER  CUS_CODE    INV_DATE
0           0        1001     10014  2012-01-16
1           1        1002     10011  2012-01-16
2           2        1003     10012  2012-01-16
3           3        1004     10011  2012-01-17
4           4        1005     10018  2012-01-17
5           5        1006     10014  2012-01-17
6           6        1007     10015  2012-01-17
7           7        1008     10011  2012-01-17

In [ ]:
#11. Count the number of invoices per customer from the invoice dataframe.

In [79]:
invoice_counts = invoice.groupby('CUS_CODE')['INV_NUMBER'].count().reset_index()

In [80]:
invoice_counts

   CUS_CODE  INV_NUMBER
0     10011           3
1     10012           1
2     10014           2
3     10015           1
4     10018           1

In [ ]:
#12. Merge the customer and invoice dataframes and show all matched and unmatched rows from both dataframes.

In [84]:
merged_df = customer.merge(invoice, on='CUS_CODE', how='outer')

In [86]:
merged_df

,Unnamed: 0_x,CUS_CODE,CUS_LNAME,CUS_FNAME,Unnamed: 0_y,INV_NUMBER,INV_DATE
0,0,10010,Ramas,Alfred,NaN,NaN,NaN
1,1,10011,Dunne,Leona,1.0,1002.0,2012-01-16
2,1,10011,Dunne,Leona,3.0,1004.0,2012-01-17
3,1,10011,Dunne,Leona,7.0,1008.0,2012-01-17
4,2,10012,Smith,Kathy,2.0,1003.0,2012-01-16
5,3,10013,Olowski,Paul,NaN,NaN,NaN
6,4,10014,Orlando,Myron,0.0,1001.0,2012-01-16
7,4,10014,Orlando,Myron,5.0,1006.0,2012-01-17
8,5,10015,O'Brian,Amy,6.0,1007.0,2012-01-17
9,6,10016,Brown,James,NaN,NaN,NaN
10,7,10017,Williams,George,NaN,NaN,NaN
11,8,10018,Farriss,Anne,4.0,1005.0,2012-01-17
12,9,10019,Smith,Olette,NaN,NaN,NaN

In [ ]:
#13. Merge the two dataframes customer and invoice into dataframe called customerInvoice using inner join. 
#   Write customerInvoice data to a customerInvoice.csv file.

In [88]:
merged_df_2 = customer.merge(invoice, how='inner', on='CUS_CODE')
merged_df_2.to_csv('customerInvoice.csv')

In [ ]:
#14. Group the invoices by customer last name and invoice date.

In [ ]:
invoice_grouped = merged_df_2.groupby(['CUS_LNAME', 'INV_DATE'])['']
invoice_grouped

In [ ]:
#15. Print the unique values for the column invoice date from the customerInvoice dataframe.

In [89]:
invoice['INV_DATE'].unique()

array(['2012-01-16', '2012-01-17'], dtype=object)